---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner
            image: registry.hub.docker.com/lrybak/scanner:dev
            imagePullPolicy: IfNotPresent
            args: 
            - "192.168.1.1/24" 
            volumeMounts:
            - name: scanner-storage
              mountPath: /mnt/scanner/
          volumes:
          - name: scanner-storage
            hostPath:
              path: /home/clouduser/scanner
              type: DirectoryOrCreate
          restartPolicy: OnFailure
