---
- hosts: localhost
  tasks:
    - name: Install Docker packages
      become: yes
      ansible.builtin.apt:
        name: 
          - docker.io=20.10.25-0ubuntu1~22.04.2
          - rsyslog=8.2112.0-2ubuntu2.2
        state: present

    - name: Adding user "{{ ansible_env.USER }}" to group docker
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_env.USER  }}"
        groups: docker
        append: yes
    
    - name: Configure Docker daemon
      become: yes
      ansible.builtin.template:
        src: templates/daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
      notify: 
        - restart rsyslog
        - restart docker

  handlers:
    - name: restart docker
      become: yes
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: restart rsyslog
      become: yes
      ansible.builtin.service:
        name: rsyslog
        state: restarted
